CREATE DATABASE if not exists EbberoedBank;
use EbberoedBank;


CREATE TABLE BANK (

BankId int AUTO_INCREMENT NOT NULL,
ByNavn VARCHAR(30) NOT NULL,
BankNavn VARCHAR(50) NOT NULL,
CONSTRAINT PK_BANK PRIMARY KEY(BankId)

);

CREATE TABLE KONTO (

KontoId int AUTO_INCREMENT NOT NULL,
Saldo float NOT NULL,
CONSTRAINT PK_KONTO PRIMARY KEY(KontoId)

);

CREATE TABLE KUNDE (

KundeId int AUTO_INCREMENT NOT NULL,
ByNavn VARCHAR(30) NOT NULL,
Navn VARCHAR(50) NOT NULL,
BankId int NOT NULL,
KontoId int NOT NULL,
CONSTRAINT PK_KUNDE PRIMARY KEY(KundeId),
CONSTRAINT FK_KUNDEKONTO FOREIGN KEY(KontoId) REFERENCES KONTO(KontoId),
CONSTRAINT FK_KUNDEBANK FOREIGN KEY(BankId) REFERENCES BANK(BankId)


);

CREATE TABLE TRANSKATION (

TranskationId int AUTO_INCREMENT NOT NULL,
Beløb float NOT NULL,
Dato datetime NOT NULL,
KontoId int NOT NULL,
CONSTRAINT PK_TRANSAKTION PRIMARY KEY(TranskationId),
CONSTRAINT FK_TRANSAKTIONKONTO FOREIGN KEY(KontoId) REFERENCES KONTO(KontoId)

);